export type MissionGuide = {
  slug: string;
  title: string;
  order: number;
  arc: "Alpha Halo" | "Operation: METEORITE";
  description: string;
  overview: string;
  priorities: string[];
  tips: string[];
  loadout: string;
  image: string;
  imageAlt: string;
};

export const missions: MissionGuide[] = [
  {
    slug: "the-pillar-of-autumn",
    title: "The Pillar of Autumn",
    order: 1,
    arc: "Alpha Halo",
    description: "A spoiler-light walkthrough and combat guide for The Pillar of Autumn, the opening Halo: Campaign Evolved mission.",
    overview: "The opening mission teaches movement, shields, grenades, weapon swapping, and the basic difference between plasma and ballistic damage while the crew evacuates the ship.",
    priorities: ["Follow the evacuation route without outrunning friendly support.", "Use plasma to strip Elite shields, then finish with precision fire.", "Enter the escape-pod sequence with ammunition rather than spending every pickup."],
    tips: ["Short bursts make the assault rifle more useful beyond point-blank range.", "Doorways create safe firing lanes when Covenant groups push together.", "On higher difficulties, retreat behind Marines instead of trading damage in open corridors."],
    loadout: "A plasma weapon paired with the pistol covers both shield damage and precision finishing.",
    image: "/media/campaign.jpg",
    imageAlt: "Halo Campaign Evolved campaign environment",
  },
  {
    slug: "halo",
    title: "Halo",
    order: 2,
    arc: "Alpha Halo",
    description: "Objectives, navigation advice, and Legendary tips for the Halo mission in Halo: Campaign Evolved.",
    overview: "The campaign opens into a broad outdoor space. The central job is to regroup with scattered Marines, survive dropship encounters, and learn how vehicles change positioning.",
    priorities: ["Locate each Marine group before leaving its area.", "Use terrain to break dropship and turret sightlines.", "Keep the Warthog mobile and stop where Marines have useful firing angles."],
    tips: ["A precision weapon helps against distant infantry across the open valleys.", "Do not park the Warthog directly under incoming dropships.", "If an encounter stalls, check the radar and surrounding elevation for one remaining enemy."],
    loadout: "Pair a precision weapon with plasma or an automatic rifle; the Warthog handles open-ground pressure.",
    image: "/media/halo-hero.jpg",
    imageAlt: "Master Chief on the Halo ring",
  },
  {
    slug: "the-truth-and-reconciliation",
    title: "The Truth and Reconciliation",
    order: 3,
    arc: "Alpha Halo",
    description: "A practical guide to The Truth and Reconciliation mission, including stealth, boarding, and rescue priorities.",
    overview: "This mission moves from a night approach into the interior of a Covenant cruiser. Long-range target selection matters outside, while room control becomes more important after boarding.",
    priorities: ["Remove exposed priority targets before the ground squad advances.", "Preserve precision ammunition for the outdoor approach.", "Inside the cruiser, clear side angles before moving into the center of a room."],
    tips: ["Let friendly units draw attention while you pick isolated targets.", "Plasma grenades are strongest when enemies funnel through narrow doors.", "Use cover between waves instead of waiting in the middle of the lift room."],
    loadout: "Keep the sniper rifle while ammunition remains, then pair a precision pickup with plasma indoors.",
    image: "/media/campaign.jpg",
    imageAlt: "Covenant environment in Halo Campaign Evolved",
  },
  {
    slug: "the-silent-cartographer",
    title: "The Silent Cartographer",
    order: 4,
    arc: "Alpha Halo",
    description: "Island route, combat priorities, and difficulty tips for The Silent Cartographer in Halo: Campaign Evolved.",
    overview: "The island assault combines beach combat, vehicle travel, interior corridors, and a return trip through previously contested ground. Route awareness saves more time than rushing.",
    priorities: ["Secure the beach before committing to the island route.", "Use the Warthog for travel but dismount before tight infantry spaces.", "Remember locked or inaccessible paths so the return route is easy to read."],
    tips: ["Clear anti-vehicle threats before circling the beach in a Warthog.", "Save grenades for clustered enemies inside the facility.", "On Legendary, pull Elites into separate fights rather than challenging the full room."],
    loadout: "A precision weapon plus plasma offers reliable coverage across the beach and facility.",
    image: "/media/halo-hero.jpg",
    imageAlt: "Halo ring landscape in Campaign Evolved",
  },
  {
    slug: "assault-on-the-control-room",
    title: "Assault on the Control Room",
    order: 5,
    arc: "Alpha Halo",
    description: "Vehicle, bridge, and infantry guidance for Assault on the Control Room in Halo: Campaign Evolved.",
    overview: "One of the campaign's longest combined-arms missions alternates between interior rooms, exposed bridges, and large vehicle spaces. Resource planning matters across the full run.",
    priorities: ["Check every major arena for a usable vehicle before advancing on foot.", "Remove turrets and heavy weapons before fighting ordinary infantry.", "Carry a ranged option for bridges and elevated platforms."],
    tips: ["Vehicles are valuable cover as well as damage sources, but damaged vehicles should not anchor a fight.", "Use door thresholds to separate pursuing enemies from ranged support.", "Keep heavy ammunition for Hunters, vehicles, and dense reinforcement waves."],
    loadout: "A precision rifle and a heavy or plasma option provide the most flexible combination.",
    image: "/media/campaign.jpg",
    imageAlt: "Large Halo Campaign Evolved combat space",
  },
  {
    slug: "343-guilty-spark",
    title: "343 Guilty Spark",
    order: 6,
    arc: "Alpha Halo",
    description: "Navigation and survival advice for the 343 Guilty Spark mission in Halo: Campaign Evolved.",
    overview: "The campaign changes tone and enemy behavior in this investigation mission. Close-range awareness, ammunition discipline, and readable retreat paths become more important.",
    priorities: ["Track the route through the facility instead of following every side corridor.", "Keep space behind you when entering unfamiliar rooms.", "Choose weapons that can answer fast close-range pressure."],
    tips: ["Reload before activating obvious encounter triggers.", "Backpedaling into an uncleared room is more dangerous than holding a known doorway.", "Use grenades to control groups, but leave enough room to avoid the blast."],
    loadout: "The shotgun is valuable at close range; pair it with an automatic weapon for sustained pressure.",
    image: "/media/campaign.jpg",
    imageAlt: "Dark campaign facility in Halo Campaign Evolved",
  },
  {
    slug: "the-library",
    title: "The Library",
    order: 7,
    arc: "Alpha Halo",
    description: "A survival-focused walkthrough for The Library, with pacing and weapon advice for higher difficulties.",
    overview: "The Library is an endurance mission built around repeated close-range attacks and movement between defensive positions. Consistent pacing is safer than sprinting into the next wave.",
    priorities: ["Stay close enough to the route marker to avoid losing progression.", "Clear active threats before crossing long exposed floors.", "Preserve a close-range weapon and replace low-ammo secondary weapons quickly."],
    tips: ["Move after each wave so enemies do not surround a static position.", "Shotgun ammunition has higher value against dangerous close-range forms.", "Use pillars and corners to limit how many enemies can reach you at once."],
    loadout: "A shotgun plus an automatic weapon is dependable; swap the secondary weapon whenever ammunition collapses.",
    image: "/media/campaign.jpg",
    imageAlt: "Forerunner architecture in Halo Campaign Evolved",
  },
  {
    slug: "two-betrayals",
    title: "Two Betrayals",
    order: 8,
    arc: "Alpha Halo",
    description: "Route planning, vehicle choices, and mixed-enemy tactics for Two Betrayals in Halo: Campaign Evolved.",
    overview: "This mission revisits familiar spaces under different combat conditions. Multiple enemy groups may fight each other, creating openings that disappear if the player attacks too early.",
    priorities: ["Let hostile factions reduce each other's numbers before intervening.", "Secure a vehicle whenever the next outdoor section supports it.", "Treat each objective area as a separate resource check."],
    tips: ["Do not become the closest target while two enemy groups are already engaged.", "A ranged weapon is useful for platforms and open snowfields.", "Save heavy shots for vehicles and targets blocking the objective route."],
    loadout: "Precision fire plus a heavy, plasma, or close-range option adapts well to the mixed encounters.",
    image: "/media/campaign.jpg",
    imageAlt: "Snowy Halo Campaign Evolved battlefield",
  },
  {
    slug: "keyes",
    title: "Keyes",
    order: 9,
    arc: "Alpha Halo",
    description: "A route and combat guide for Keyes, the ninth Alpha Halo mission in Halo: Campaign Evolved.",
    overview: "Keyes returns to Covenant spaces with heavier close-range pressure and less predictable crossfire. The safest approach is to keep a clear exit and avoid fighting every faction at once.",
    priorities: ["Identify the route before committing to lower or enclosed spaces.", "Use enemy-on-enemy combat to conserve ammunition.", "Enter major interior encounters with a close-range answer ready."],
    tips: ["Stay near the edge of multi-faction fights until priority targets fall.", "Check dropped weapons after each room rather than carrying an empty favorite.", "Grenades are best used to block pursuit, not thrown into uncertain close-range space."],
    loadout: "A shotgun or automatic weapon paired with plasma or precision fire covers the varied interior fights.",
    image: "/media/campaign.jpg",
    imageAlt: "Covenant cruiser interior in Halo Campaign Evolved",
  },
  {
    slug: "the-maw",
    title: "The Maw",
    order: 10,
    arc: "Alpha Halo",
    description: "Final-mission objectives, combat pacing, and escape advice for The Maw in Halo: Campaign Evolved.",
    overview: "The Alpha Halo finale combines shipboard combat, timed pressure, and a vehicle escape. The mission rewards clean execution more than exhaustive searching.",
    priorities: ["Keep moving through cleared ship sections instead of rechecking empty rooms.", "Save durable weapons for the objective rooms that force close combat.", "During the escape, prioritize a stable route over unnecessary speed."],
    tips: ["Reload and collect ammunition before beginning a timed sequence.", "Use short corrections in the Warthog rather than oversteering after every impact.", "If the escape repeatedly fails, learn the safe line through one section at a time."],
    loadout: "Carry one dependable close-range weapon and one flexible mid-range option before the final sequence.",
    image: "/media/halo-hero.jpg",
    imageAlt: "Master Chief in the Halo Campaign Evolved finale",
  },
  {
    slug: "boarding-action",
    title: "Boarding Action",
    order: 11,
    arc: "Operation: METEORITE",
    description: "Confirmed details and spoiler-light preparation for Boarding Action in Operation: METEORITE.",
    overview: "Boarding Action opens the three-mission Operation: METEORITE prequel. Official material places the operation one year before Alpha Halo and pairs Master Chief with Sergeant Avery Johnson.",
    priorities: ["Treat new encounter layouts as unknown rather than relying on original-campaign routes.", "Check the objective marker after large fights before searching side spaces.", "Keep complementary shield-breaking and finishing weapons."],
    tips: ["Use the first encounter to test how the current difficulty changes enemy aggression.", "Preserve heavy ammunition until the mission establishes its priority targets.", "In co-op, assign one player to ranged control and another to close support."],
    loadout: "Start with complementary damage types and adjust when the mission reveals its dominant engagement range.",
    image: "/media/operation-meteorite.jpg",
    imageAlt: "Master Chief and Sergeant Johnson in Operation Meteorite",
  },
  {
    slug: "the-most-dangerous-game",
    title: "The Most Dangerous Game",
    order: 12,
    arc: "Operation: METEORITE",
    description: "Spoiler-light objectives and preparation for The Most Dangerous Game in Halo: Campaign Evolved.",
    overview: "The Most Dangerous Game is the middle chapter of Operation: METEORITE. This guide limits itself to confirmed placement and broadly useful preparation until encounter-specific details can be checked against the live build.",
    priorities: ["Review the previous mission's successful weapon roles before changing both slots.", "Pause at major route branches and confirm the active objective.", "Keep the squad together when entering unfamiliar combat spaces."],
    tips: ["Avoid publishing or following unverified collectible routes during the launch window.", "Use checkpoint timing to identify when an encounter has fully ended.", "On higher difficulties, stagger player pushes so one teammate can recover safely."],
    loadout: "A balanced precision and shield-control pairing is safer than two specialized power weapons.",
    image: "/media/operation-meteorite.jpg",
    imageAlt: "Operation Meteorite campaign art",
  },
  {
    slug: "heavy-burden",
    title: "Heavy Burden",
    order: 13,
    arc: "Operation: METEORITE",
    description: "A spoiler-light guide and readiness checklist for Heavy Burden, the Operation: METEORITE finale.",
    overview: "Heavy Burden concludes the prequel arc. The page focuses on loadout planning, co-op discipline, and verified campaign structure without inventing boss phases or collectible locations.",
    priorities: ["Enter the finale with a flexible loadout rather than two low-ammo power weapons.", "Clear supporting enemies before focusing on a single durable target.", "Keep an obvious fallback position available during unfamiliar waves."],
    tips: ["Use a failed attempt to identify damage types and safe positions, not just to repeat the same push.", "In co-op, call out heavy-ammo pickups before one player consumes them.", "Confirm the mission-complete state before leaving optional combat areas."],
    loadout: "Combine reliable mid-range damage with a weapon that handles shields, groups, or close pressure.",
    image: "/media/operation-meteorite.jpg",
    imageAlt: "Operation Meteorite finale art",
  },
];

export function getMission(slug: string) {
  return missions.find((mission) => mission.slug === slug);
}
